import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRef, useState } from 'react';
import parser from './otp.js';
import { StyleRegistry } from 'styled-jsx';

export default function Home() {
  const inputEl = useRef(null);
  const [list, setList] = useState([]);

  const parseURL = () => {
    const url = inputEl.current.value;
    console.log(url);
    try {
      const list = parser(url);
      setList(list);
    } catch (e) {
      setList([])
      // error
    }


  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Google Authenticator To oathtool / openconnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Google Auth &gt; oathtool
        </h1>

        <div className={styles.description}>
          <textarea ref={inputEl} type="text" placeholder="Paste otpauth-migration:// URL here..." className={styles.largeinput} onChange={parseURL} name="oauth-migration-url" />
          <div>
          <button onClick={parseURL}>Update</button>
          </div>
        </div>

        <div className={styles.grid}>
          {list.map((el, index) => <div key={index}>
            <h3>{el.name} ({el.issuer})</h3>
            {el.type == 'totp' ?
              <div className={styles.code}>
                <span className={styles.prompt}>$</span> <code>oathtool -b --totp={el.algorithm} -d {el.digits} {el.secret}</code><br/>
                <span className={styles.prompt}>$</span> <code>sudo openconnect --user=$USER --token-mode=totp --token-secret={el.algorithm}:base32:{el.secret} $URL</code>
              </div>
              :
              <></>
            }

          </div>)}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
